import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import NavBar from '@/component/Nav'
import Body from '@/component/Body'
import Loading from '@/component/loading/loading'
import React,{useState} from 'react'
import LandingPage from '@/component/LandingPage';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [loading, setLoading] = useState(false);

  if(loading)
  {
   return <Loading loading={loading}/>
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <LandingPage/>
      <Body/>
    </>
  )
}
